# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [30]:
import numpy as np


In [35]:
a = np.arange(1,12)
print(a)
b = a
a [2:6]=-a[2:6]
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [39]:
A = np.random.rand(3, 6)
print(A)
A[A>0.5]
print(A.size)

[[0.91770974 0.95828198 0.16126539 0.2810787  0.27026153 0.18161094]
 [0.01317133 0.25927406 0.62604199 0.65669279 0.19275637 0.34958225]
 [0.73843978 0.02659052 0.56720744 0.15955427 0.45511635 0.20527058]]
18
