# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
沒有

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
import numpy as np

In [30]:
A = np.random.random((5, 5))
print(A)
Amax=A.max()
Amin=A.min()
print(Amax)
print(Amin)
B = (A - Amin) / (Amax-Amin)
print(B)


[[0.63887761 0.13596484 0.88576282 0.09600186 0.57125891]
 [0.89247252 0.37786538 0.27808752 0.16692883 0.07072344]
 [0.27992005 0.75004702 0.09099524 0.75041186 0.35305702]
 [0.08765983 0.79885344 0.16842778 0.93013156 0.59937946]
 [0.64465882 0.08460079 0.34972591 0.05919836 0.40613473]]
0.9301315550401624
0.059198361751718886
[[0.66558406 0.08814278 0.9490561  0.04225754 0.58794469]
 [0.95676013 0.36589146 0.25132715 0.12369545 0.01323302]
 [0.25343125 0.79322807 0.03650898 0.79364698 0.33740665]
 [0.03267927 0.84926729 0.12541653 1.         0.62023253]
 [0.67222201 0.0291669  0.3335819  0.         0.39835015]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [47]:
x = np.random.randint(1,16,10)
print(x)
y = np.argmax(x)
print(y)
x[y] = -1
print(x)

[11 15  2 10  7 12 12 12 15 10]
1
[11 -1  2 10  7 12 12 12 15 10]
